"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY="mse_superbrain_v3", MAX_IMPORT=1024*1024;
const defaults=()=>({version:3,prompt:{role:"",task:"",format:"",constraint:"",out:""},ai:{gpt:"",gemini:"",grok:"",result:""},tasks:[],timer:{duration:300},settings:{theme:"system",font:"small",sound:true,vibrate:true}});
function merge(raw){const d=defaults();return {...d,...raw,prompt:{...d.prompt,...raw?.prompt},ai:{...d.ai,...raw?.ai},timer:{...d.timer,...raw?.timer},settings:{...d.settings,...raw?.settings},tasks:Array.isArray(raw?.tasks)?raw.tasks.slice(0,500):[]}}
function load(){try{return merge(JSON.parse(localStorage.getItem(KEY)||"null"))}catch{return defaults()}}
let state=load(), page="home", timerId=null, endAt=0, remain=state.timer.duration, running=false, installPrompt=null;
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast("儲存空間不足，請先匯出備份")}};
const debounce=(fn,ms=350)=>{let id;return()=>{clearTimeout(id);id=setTimeout(fn,ms)}}; const lazySave=debounce(save);
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(el._id);el._id=setTimeout(()=>el.classList.remove("show"),2300)}
function pulse(){if(state.settings.vibrate&&navigator.vibrate)navigator.vibrate(18)}
function go(name){if(!$( `[data-page="${name}"]`))return;page=name;$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$("#backBtn").classList.toggle("hidden",name==="home");window.scrollTo({top:0,behavior:"smooth"});history.replaceState(null,"",name==="home"?location.pathname:`#${name}`);$("h1").focus?.();pulse()}
function theme(){let t=state.settings.theme;if(t==="system")t=matchMedia("(prefers-color-scheme: light)").matches?"light":"dark";document.documentElement.dataset.theme=t;document.documentElement.dataset.font=state.settings.font}
function hydrate(){["role","task","format","constraint"].forEach(k=>$("#"+k).value=state.prompt[k]||"");$("#promptOut").value=state.prompt.out||"";["gpt","gemini","grok","result"].forEach(k=>$("#"+k).value=state.ai[k]||"");$("#promptResultBox").classList.toggle("hidden",!state.prompt.out);$("#compareResultBox").classList.toggle("hidden",!state.ai.result);$("#themeSelect").value=state.settings.theme;$("#fontSelect").value=state.settings.font;$("#soundToggle").checked=state.settings.sound;$("#vibrateToggle").checked=state.settings.vibrate;remain=state.timer.duration;renderTimer();renderTasks();theme()}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function copy(text){try{await navigator.clipboard.writeText(text);toast("已複製") }catch{toast("瀏覽器未允許複製，請長按文字手動複製")}}
function md(){const content=state.ai.result||state.prompt.out;if(!content)return toast("目前沒有可匯出的內容");download(`MSE_NotebookLM_${new Date().toISOString().slice(0,10)}.md`,content,"text/markdown;charset=utf-8");toast("Markdown 已匯出")}
function buildPrompt(e){e.preventDefault();const task=$("#task").value.trim();if(!task)return toast("請先填寫任務");state.prompt={role:$("#role").value.trim(),task,format:$("#format").value.trim(),constraint:$("#constraint").value.trim(),out:`你是一位${$("#role").value.trim()?`「${$("#role").value.trim()}」`:"能精準釐清需求的專業助理"}。\n\n【任務】\n${task}\n\n【輸出格式】\n${$("#format").value.trim()||"使用清楚的台灣繁體中文與分層條列"}\n\n【限制與品質要求】\n${$("#constraint").value.trim()||"先確認資訊是否充分；不確定處須標明，不可捏造。"}\n\n【執行原則】\n先給結論，再提供可執行步驟；如涉及敏感、醫療、金融或身分資料，先提出安全提醒。`};$("#promptOut").value=state.prompt.out;$("#promptResultBox").classList.remove("hidden");save();toast("Prompt 已生成");$("#promptResultBox").scrollIntoView({behavior:"smooth"})}
function compare(e){e.preventDefault();const entries=[["ChatGPT",$("#gpt").value.trim()],["Gemini",$("#gemini").value.trim()],["Grok",$("#grok").value.trim()]].filter(x=>x[1]);if(!entries.length)return toast("請至少貼上一份 AI 回覆");state.ai.result=`# 多模型交叉裁定工作稿\n\n${entries.map(([n,v])=>`## ${n}\n${v}`).join("\n\n")}\n\n## 待裁定清單\n1. 三方一致的結論：\n2. 彼此衝突或需查證之處：\n3. 最可靠且可執行的建議：\n4. 風險、假設與資料缺口：\n\n> 注意：以上為結構化彙整草稿，仍需人工或可信來源完成最終查證。`;$("#result").value=state.ai.result;$("#compareResultBox").classList.remove("hidden");save();toast("裁定工作稿已生成")}
function renderTimer(){const sec=Math.max(0,Math.round(remain)),m=String(Math.floor(sec/60)).padStart(2,"0"),s=String(sec%60).padStart(2,"0");$("#timerText").textContent=`${m}:${s}`;$("#timerProgress").style.width=`${Math.min(100,(1-sec/state.timer.duration)*100)}%`;$("#timerStatus").textContent=running?"專注中":sec<state.timer.duration&&sec>0?"已暫停":sec===0?"已完成":"準備開始";$("#startBtn").textContent=running?"暫停":sec<state.timer.duration&&sec>0?"繼續":"開始"}
function tick(){remain=Math.max(0,(endAt-Date.now())/1000);renderTimer();if(remain<=0){clearInterval(timerId);timerId=null;running=false;remain=0;renderTimer();finishTimer()}}
function setTimer(sec){clearInterval(timerId);timerId=null;running=false;state.timer.duration=sec;remain=sec;save();renderTimer();toast(`已設定 ${Math.round(sec/60)} 分鐘`)}
function toggleTimer(){if(running){remain=Math.max(0,(endAt-Date.now())/1000);clearInterval(timerId);timerId=null;running=false}else{if(remain<=0)remain=state.timer.duration;running=true;endAt=Date.now()+remain*1000;timerId=setInterval(tick,250)}renderTimer();pulse()}
function finishTimer(){if(state.settings.vibrate&&navigator.vibrate)navigator.vibrate([150,80,150]);if(state.settings.sound){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.value=.12;o.connect(g).connect(c.destination);o.start();setTimeout(()=>{o.stop();c.close()},550)}catch{}}toast("時間到，請休息一下")}
function renderTasks(){const box=$("#tasks"),done=state.tasks.filter(t=>t.done).length;$("#taskCounter").textContent=state.tasks.length?`${done} / ${state.tasks.length} 已完成`:"尚無任務";box.replaceChildren();if(!state.tasks.length){const e=document.createElement("div");e.className="empty";e.textContent="新增第一項任務，開始鍛造行動。";box.append(e);return}state.tasks.forEach(t=>{const row=document.createElement("div");row.className=`task-item${t.done?" done":""}`;row.dataset.id=t.id;const b=document.createElement("button");b.className="task-toggle";b.dataset.taskToggle=t.id;b.textContent=t.text;b.setAttribute("aria-pressed",String(t.done));const d=document.createElement("button");d.className="task-delete";d.dataset.taskDelete=t.id;d.textContent="🗑";d.setAttribute("aria-label",`刪除任務：${t.text}`);row.append(b,d);box.append(row)})}
function validImport(x){return x&&typeof x==="object"&&(!x.tasks||Array.isArray(x.tasks))&&(!x.prompt||typeof x.prompt==="object")&&(!x.ai||typeof x.ai==="object")&&(!x.settings||typeof x.settings==="object")}
function selfTest(){const tests=[];const test=(n,fn)=>{try{tests.push(`${fn()?"✅":"❌"} ${n}`)}catch{tests.push(`❌ ${n}`)}};test("必要畫面與按鈕存在",()=>$$('.page').length===6&&!!$("#startBtn"));test("本機儲存可讀寫",()=>{localStorage.setItem("__mse_test","1");const ok=localStorage.getItem("__mse_test")==="1";localStorage.removeItem("__mse_test");return ok});test("匯入驗證拒絕陣列",()=>!validImport([]));test("任務文字採安全 DOM 輸出",()=>renderTasks()===undefined);test("PWA Service Worker 支援偵測",()=>"serviceWorker" in navigator||location.protocol==="file:");test("未載入外部雲端程式",()=>$$('script[src]').every(s=>new URL(s.src).origin===location.origin));$("#selfTestOut").textContent=tests.join("\n");toast(tests.some(x=>x.startsWith("❌"))?"檢測完成，請查看未通過項目":"自我檢測全數通過")}
document.addEventListener("click",e=>{const goBtn=e.target.closest("[data-go]");if(goBtn)return go(goBtn.dataset.go);const a=e.target.closest("[data-action]");if(a){const act=a.dataset.action;if(act==="copy-prompt")copy($("#promptOut").value);if(act==="copy-result")copy($("#result").value);if(act==="export-md")md();if(act==="open-ai-picker"){if(!state.prompt.out)return toast("請先生成 Prompt");$("#aiDialog").showModal()}if(act==="toggle-timer")toggleTimer();if(act==="reset-timer")setTimer(state.timer.duration);if(act==="clear-completed"){if(!state.tasks.some(t=>t.done))return toast("沒有已完成任務");if(confirm("清除所有已完成任務？")){state.tasks=state.tasks.filter(t=>!t.done);save();renderTasks()}}if(act==="export-json")download(`MSE_backup_${Date.now()}.json`,JSON.stringify(state,null,2),"application/json");if(act==="import-json")$("#importFile").click();if(act==="self-test")selfTest();if(act==="clear-data"&&confirm("確定清除所有本機資料？請先匯出備份；此動作無法復原。")){localStorage.removeItem(KEY);state=defaults();hydrate();toast("本機資料已清除")}}const preset=e.target.closest("[data-seconds]");if(preset)setTimer(Number(preset.dataset.seconds));const ai=e.target.closest("[data-ai-url]");if(ai){copy(state.prompt.out);window.open(ai.dataset.aiUrl,"_blank","noopener,noreferrer")}const toggle=e.target.closest("[data-task-toggle]");if(toggle){const t=state.tasks.find(x=>x.id===toggle.dataset.taskToggle);if(t){t.done=!t.done;save();renderTasks();pulse()}}const del=e.target.closest("[data-task-delete]");if(del){state.tasks=state.tasks.filter(x=>x.id!==del.dataset.taskDelete);save();renderTasks()}});
$("#backBtn").addEventListener("click",()=>go("home"));$("#settingsBtn").addEventListener("click",()=>$("#settingsDialog").showModal());$("#promptForm").addEventListener("submit",buildPrompt);$("#compareForm").addEventListener("submit",compare);$("#customTimerForm").addEventListener("submit",e=>{e.preventDefault();const n=Number($("#customMin").value);if(!Number.isInteger(n)||n<1||n>180)return toast("請輸入 1–180 的整數分鐘");setTimer(n*60)});$("#taskForm").addEventListener("submit",e=>{e.preventDefault();const input=$("#taskInput"),text=input.value.trim();if(!text)return toast("請輸入任務");state.tasks.unshift({id:crypto.randomUUID?.()||`t_${Date.now()}`,text,done:false,createdAt:Date.now()});input.value="";save();renderTasks();toast("任務已新增")});
["role","task","format","constraint","gpt","gemini","grok","promptOut","result"].forEach(id=>$("#"+id).addEventListener("input",()=>{if(["gpt","gemini","grok","result"].includes(id))state.ai[id]=$("#"+id).value;else state.prompt[id==="promptOut"?"out":id]=$("#"+id).value;lazySave()}));
$("#themeSelect").addEventListener("change",e=>{state.settings.theme=e.target.value;theme();save()});$("#fontSelect").addEventListener("change",e=>{state.settings.font=e.target.value;theme();save()});$("#soundToggle").addEventListener("change",e=>{state.settings.sound=e.target.checked;save()});$("#vibrateToggle").addEventListener("change",e=>{state.settings.vibrate=e.target.checked;save()});
$("#importFile").addEventListener("change",async e=>{const f=e.target.files[0];e.target.value="";if(!f)return;if(f.size>MAX_IMPORT)return toast("檔案超過 1 MB，已拒絕匯入");try{const x=JSON.parse(await f.text());if(!validImport(x))throw Error();state=merge(x);save();hydrate();toast("備份已安全匯入")}catch{toast("匯入失敗：不是有效的 MSE JSON 備份")}});
addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").addEventListener("click",async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("#installBtn").classList.add("hidden")});document.addEventListener("visibilitychange",()=>{if(!document.hidden&&running)tick()});matchMedia("(prefers-color-scheme: light)").addEventListener?.("change",theme);
if("serviceWorker" in navigator&&location.protocol.startsWith("http"))addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>toast("離線功能暫未啟用")));
hydrate();go((location.hash.slice(1)&&$( `[data-page="${location.hash.slice(1)}"]`))?location.hash.slice(1):"home");
